[package]
description = "Arrow svc-gis GRPC client"
name        = "svc-gis-client-grpc"
version     = "0.0.1-develop.2"

categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license-file.workspace = true
repository.workspace   = true

[dependencies]
chrono      = "0.4"
prost       = "0.11"
prost-types = "0.11"
tonic       = "0.8"
uuid        = { version = "1.3", features = ["v4"] }

[dependencies.lib-common]
git = "https://github.com/Arrow-air/lib-common.git"
tag = "v0.1.1-develop.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
